ahadis/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'ahadis'
urlpatterns = [
    path('save_hadis_page', cache_page(60000)(views.save_hadis_page), name='save_hadis_page'),
    path('show', views.show, name='show'),
    path('save_book_page', cache_page(60000)(views.save_book_page), name='save_book_page'),
    path('save_hadis', views.save_hadis, name='save_hadis'),
    path('save_book', views.save_book, name='save_book'),
    path('search', views.search, name='search'),
    path('filter_ahadis_from_fehrest', views.filter_ahadis_from_fehrest, name='filter_ahadis_from_fehrest'),
    path('filter_ahadis_from_fehrest_subject', views.filter_ahadis_from_fehrest_subject, name='filter_ahadis_from_fehrest_subject'),
    path('check_hadis_repetition', views.check_hadis_repetition, name='check_hadis_repetition'),
    # path('test', views.test, name='test'),
]

kalamenoor/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ahadis/', include('ahadis.urls')),
    path('admin/', admin.site.urls),
]

ahadis/models.py
from django.db import models


class Narration(models.Model):
    narration_text = models.CharField(max_length=20000)
    # date = models.DateTimeField('date')

ahadis/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import pyodbc
import pandas as pd
import numpy as np
import json
from .utils import conn



# Create your views here.
def save_hadis_page(request):
    df = pd.read_sql_query('select * from dbo.Book', conn)
    df_json_str = df.to_json(orient="records")
    df_json = json.loads(df_json_str)

    masoumin = get_masoumin()
    return render(request, 'ahadis/save_hadis.html',
                  {'books': df_json, 'masoumin': masoumin,
                   'summaries_counter': range(1, 71), 'subjects_counter': range(1, 16),
                   'summaries_ayat_counter': range(1, 71), 'summaries_containing_ayat_counter': range(1, 36),
                   'related_explanation_counter': range(1, 71)})


def get_intersection_of_hadis_to_others(hadis, others):
    def get_intersection_of_hadis_to_1_other(hadis, other):
        def lambda_map(x):
            if x == ' ':
                return -1
            elif x in splited_other:
                return 1
            else:
                return 0

        splited_hadis = hadis.split(' ')
        splited_other = other.split(' ')
        intersection_boolean = [(word in splited_other) & (word != ' ') for word in splited_hadis]
        intersection = list(map(lambda_map, splited_hadis))
        intersection = np.array(intersection)
        intersection_percent = sum(intersection == 1) / sum(intersection != -1) * 100
        return intersection_percent, intersection

    for h in others:
        intersection_percent, intersection = get_intersection_of_hadis_to_1_other(hadis, h)
        if intersection_percent > 80:
            return intersection, h
    else:
        return None, None


def check_hadis_repetition(request):
    hadis_text = request.POST['HadisTextForRepetition']
    if not hadis_text:
        return HttpResponse('متن حدیث را وارد نکردید')
    else:
        ahadis = get_ahadis()['Had_Text'].to_list()
        intersection, other = get_intersection_of_hadis_to_others(hadis_text, ahadis)
        if intersection is None:
            return HttpResponse('این حدیث تکراری نیست')
        else:
            splited = np.array(hadis_text.split(' '))
            intersection_cond = list(map(lambda x: x == 1, intersection))
            intersection_hadis = ' '.join(splited[intersection_cond])

            result_text_1 = 'حدیث تکراری است. کلمات زیر در یک حدیث دیگر وجود دارد'
            result_text_2 = 'حدیثی که در دیتابیس وجود دارد ' + '\n'

            # return HttpResponse(f'{result_text_1} \n {intersection_hadis} \n\n\n {result_text_2} \n {other}')

    return render(request, 'ahadis/check_hadis_repetition.html',
                  {'result_text_1': result_text_1, 'result_text_2': result_text_2,
                   'intersection_hadis': intersection_hadis, 'other': other})


def save_hadis(request):
    hadis_text = request.POST['HadisText']
    hadis_text = hadis_text if hadis_text else 'NULL'
    hadis_name = request.POST['HadisName']
    hadis_name = hadis_name if hadis_name else 'NULL'
    masoum_id = request.POST['MasoumID']
    masoum_id = masoum_id if masoum_id else 'NULL'
    hadis_narrators = request.POST['HadisNarrators']
    hadis_narrators = hadis_narrators if hadis_narrators else 'NULL'
    book_vol_no = request.POST['BookVolNo']
    book_vol_no = book_vol_no if book_vol_no else 'NULL'
    book_page_no = request.POST['BookPageNo']
    book_page_no = book_page_no if book_page_no else 'NULL'
    book_hadis_no = request.POST['BookHadisNo']
    book_hadis_no = book_hadis_no if book_hadis_no else 'NULL'

    book_id = request.POST['BookID']

    subjects = [request.POST[f'HadisSubject{i}'] for i in range(1, 16)]

    ayat = [{'soore_name': request.POST[f'ContainingAyatSoore{i}'],
             'aye_no': request.POST[f'ContainingAyatAye{i}']} for i in range(1, 36)]

    related_explanation = [{'expression': request.POST[f'Expression{i}'],
                            'explanation': request.POST[f'Explanation{i}']} for i in range(1, 71)]

    ayat_summaries_in_fehrest = [{'alphabet': request.POST[f'FehrestSoore{i}'],
                                  'subject': request.POST[f'FehrestAyeNo{i}'],
                                  'summary': request.POST[f'FehrestAyeText{i}']} for i in range(1, 71)]

    summaries_in_fehrest = [{'alphabet': request.POST[f'Alphabet{i}'],
                             'subject': request.POST[f'Subject{i}'],
                             'summary': request.POST[f'Text{i}']} for i in range(1, 71)]

    had_id = get_had_id_for_insert_to_hadis_table()

    cursor = conn.cursor()
    cursor.execute(
        "insert into dbo.Hadis(Had_ID, Had_Text, Had_Title, MasoumID, Had_Narrators, "
        "Boo_ID, Had_BookVolNo, Had_BookPageNo, Had_BookHadisNo) "
        f"values({had_id}, N'{hadis_text}', N'{hadis_name}', {masoum_id}, N'{hadis_narrators}', "
        f"{book_id}, {book_vol_no}, {book_page_no}, {book_hadis_no})")

    cursor.commit()
    cursor.close()

    cursor = conn.cursor()
    for subject in subjects:
        if subject:
            cursor.execute(f"INSERT INTO dbo.HadisSubject(Had_ID, HadS_Subject) VALUES({had_id}, N'{subject}')")
    cursor.commit()
    cursor.close()

    cursor = conn.cursor()
    for item in summaries_in_fehrest:
        if item['subject'] and item['alphabet']:
            item['summary'] = item['summary'] if item['summary'] else 'NULL'
            cursor.execute(
                f"INSERT INTO dbo.HadisSummaryInFehrest(Had_ID, HadSIF_Alphabet, HadSIF_subject, HadSIF_Summary) "
                f"VALUES({had_id}, N'{item['alphabet']}', N'{item['subject']}', N'{item['summary']}')")
    cursor.commit()
    cursor.close()

    cursor = conn.cursor()
    for item in ayat:
        if item['soore_name'] and item['aye_no']:
            # item['soore_name'] = item['soore_name'] if item['soore_name'] else 'NULL'
            cursor.execute(
                f"INSERT INTO dbo.[AyatInHadis](Had_ID, [AyaIH_SooreName], [AyaIH_AyeNo]) "
                f"VALUES({had_id}, N'{item['soore_name']}', {item['aye_no']})")
    cursor.commit()
    cursor.close()

    return HttpResponseRedirect(reverse('ahadis:save_hadis_page'))


def show(request, had_ids=None):
    df_json = get_ahadis(had_ids, in_json_format=True)
    fehrest_json = get_ahadis_fehrest(in_hierarchy_format=True)
    ayat_fehrest_json = get_ayat_fehrest(in_hierarchy_format=True)
    ayat_fehrest_serial_json = get_ayat_fehrest_serial(in_hierarchy_format=True)
    return render(request, 'ahadis/show.html', {'ahadis': df_json, 'fehrest': fehrest_json,
                                                'ayat_fehrest': ayat_fehrest_json,
                                                'ayat_fehrest_serial': ayat_fehrest_serial_json})


def save_book_page(request):
    return render(request, 'ahadis/save_book.html')


def save_book(request):
    name = request.POST['Name']
    publisher = request.POST['Publisher']
    author = request.POST['Author']
    subject = request.POST['Subject']
    language = request.POST['Language']

    cursor = conn.cursor()
    cursor.execute("insert into dbo.Book(Boo_Title, Boo_Author, Boo_Publisher, Boo_Language, Boo_Subject) "
                   f"values(N'{name}', N'{author}', N'{publisher}', N'{language}', N'{subject}')")
    cursor.commit()
    cursor.close()

    return HttpResponseRedirect(reverse('ahadis:save_book_page'))


def search(request):
    word1 = request.POST['word1']
    word2 = request.POST['word2']
    word3 = request.POST['word3']
    word4 = request.POST['word4']

    word1 = word1 if word1 else ''
    word2 = word2 if word2 else ''
    word3 = word3 if word3 else ''
    word4 = word4 if word4 else ''

    subject1 = request.POST['subject1']
    subject2 = request.POST['subject2']
    subject3 = request.POST['subject3']
    subject4 = request.POST['subject4']

    subject1 = subject1 if subject1 else None
    subject2 = subject2 if subject2 else None
    subject3 = subject3 if subject3 else None
    subject4 = subject4 if subject4 else None

    df = get_ahadis()
    df = filter_ahadis(df, [word1, word2, word3, word4], [subject1, subject2, subject3, subject4])
    df_json_str = df.to_json(orient="records")
    df_json = json.loads(df_json_str)
    fehrest_json = get_ahadis_fehrest(in_hierarchy_format=True)
    return render(request, 'ahadis/show.html', {'ahadis': df_json, 'fehrest': fehrest_json})


def filter_ahadis(ahadis_df, words, requested_subjects):
    if len(ahadis_df) > 0:
        ahadis_df = ahadis_df[
            ahadis_df['Had_Text'].apply(lambda x: all([word in remove_arabic_characters(x) for word in words]))]
        subjects = get_ahadis_subjects()
        ahadis_df = filter_ahadis_to_requested_subjects(ahadis_df, subjects, requested_subjects)
    return ahadis_df


def filter_ahadis_from_fehrest(request):
    had_id = request.POST['had_id']
    had_id = had_id if had_id else None

    df_json = get_ahadis(had_id, in_json_format=True)

    fehrest_json = get_ahadis_fehrest(in_hierarchy_format=True)
    return render(request, 'ahadis/show.html', {'ahadis': df_json, 'fehrest': fehrest_json})


def filter_ahadis_from_fehrest_subject(request):
    subject = request.POST['Subject']
    subject = subject if subject else None

    fehrest = get_ahadis_fehrest()
    had_ids = fehrest['Had_ID'][fehrest['HadSIF_subject'] == subject].unique()

    df_json = get_ahadis(had_ids, in_json_format=True)

    fehrest_json = get_ahadis_fehrest(in_hierarchy_format=True)
    return render(request, 'ahadis/show.html', {'ahadis': df_json, 'fehrest': fehrest_json})


def remove_arabic_characters(string):
    to_get_replaced_characters = 'آةيؤإأۀ'
    replacers = 'اهیوااه'

    saken_dar = 'بْنُ'
    saken = saken_dar[1]
    to_be_removed_characters = 'ءًٌٍَُِّ' + saken

    my_table = string.maketrans(to_get_replaced_characters, replacers, to_be_removed_characters)
    result = string.translate(my_table)

ahadis/templates/ahadis/base.html
<!DOCTYPE html>
<html>
<head>
    <title>کلام نور</title>
    {% load static %}
    <link href="{% static 'ahadis/index.css' %}" rel="stylesheet"/>
</head>
<body>
<div id="HeaderContainer">
    <div id="HeaderContent"> جنة المأوی</div>
    <div id="MainButtons">
        <a href="{% url 'ahadis:save_book_page' %}">
            <Button id="SaveBookButton" onclick="">ذخیره کتاب</Button>
        </a>
        <a href="{% url 'ahadis:show' %}">
            <Button id="ShowButton" onclick="">نمایش حدیث ها</Button>
        </a>
        <a href="{% url 'ahadis:save_hadis_page' %}">
            <Button id="SaveHadisButton" onclick="">ذخیره حدیث</Button>
        </a>
    </div>
</div>
{% block content %}
{% endblock content %}
{% block js %}
{% endblock js %}
    <script src="{% static 'ahadis/base.js' %}"></script>
</body>
</html>

ahadis/templates/ahadis/check_hadis_repetition.html
<!DOCTYPE html>
{% extends "ahadis/base.html" %}
{% block content %}
{% load static %}
<link href="{% static 'ahadis/check_hadis_repetition.css' %}" rel="stylesheet"/>
<div id="intersection">
    <h3>
       : {{ result_text_1 }}
    </h3>
    <div>
        {{ intersection_hadis }}
    </div>
</div>
<div id="database">
    <h3>
       : {{ result_text_2 }}
    </h3>
    <div>
        {{ other }}
    </div>
</div>
{% endblock content %}

ahadis/templates/ahadis/save_book.html
<!DOCTYPE html>
{% extends "ahadis/base.html" %}
{% block content %}
{% load static %}
    <link href="{% static 'ahadis/save_book.css' %}" rel="stylesheet"/>
        <form action="{% url 'ahadis:save_book' %}" method="post">
            {% csrf_token %}

            <input class="InputOne" placeholder="نام کتاب" type="text" name="Name"/>
            <input class="InputOne" placeholder="چاپ" type="text" name="Publisher"/>
            <input class="InputOne" placeholder="مولف" type="text" name="Author"/>
            <input class="InputOne" placeholder="موضوع" type="text" name="Subject"/>
            <input class="InputOne" placeholder="زبان" type="text" name="Language"/>
            <Button id="SubmitButton" onclick="">ذخیره</Button>
        </form>
{% endblock content %}

ahadis/templates/ahadis/save_hadis.html
<!DOCTYPE html>
{% extends "ahadis/base.html" %}
{% load static %}
{% block content %}
{% load static %}
    <link href="{% static 'ahadis/save_hadis.css' %}" rel="stylesheet"/>
    <form id="SaveAhadis" action="{% url 'ahadis:save_hadis' %}" method="post">
        {% csrf_token %}
                    اطلاعات شناسنامه ای حدیث
        <br>
            <input class="InputOne" placeholder="نام حدیث" type="text" name="HadisName"/>
           <select id="Masoum" class="InputOne" name="MasoumID">
                {% for masoum in masoumin %}
                    <option class="InputOne" value="{{masoum.MasoumID}}">{{masoum.MasoumName}}</option>
                {% endfor %}
            </select>
            <input class="InputOne" placeholder="راویان حدیث" type="text" name="HadisNarrators"/>
            <input class="InputOne" placeholder="متن حدیث" type="text" name="HadisText"/>
            <select class="InputOne" name="BookID">
                {% for book in books %}
                    <option class="InputOne" value="{{book.Boo_ID}}">{{book.Boo_Title}}</option>
                {% endfor %}
            </select>
            <input class="InputOne" placeholder="شماره جلد کتاب" type="text" name="BookVolNo"/>
            <input class="InputOne" placeholder="شماره صفحه" type="text" name="BookPageNo"/>
            <input class="InputOne" placeholder="شماره حدیث" type="text" name="BookHadisNo"/>
            <br>
            موضوعات مرتبط با حدیث
            <br>
            {% for i in subjects_counter %}
                <input class="InputSubject" type="text" name="HadisSubject{{i}}"/>
            {% endfor %}
            <br>
        <div id="SummaryContainer">
            <div class="FloatLeft" id="FehrestSummaryContainer">
                <div id="FehrestSummaryContainerTitle">خلاصه ها و فهرست</div>
                {% for i in summaries_counter %}
                <div id="FehrestSummaryObject{{i}}" class="FehrestSummaryObject">
                    {{forloop.counter}}-
                    <input type="text" placeholder="حرف الفبا" name="Alphabet{{i}}"/>
                    <input type="text" placeholder="موضوع" name="Subject{{i}}"/>
                    <input type="text" placeholder="خلاصه" name="Text{{i}}"/>
                </div>
                {% endfor %}
            </div>
            <div class="FloatLeft" id="ContainingAyatContainer">
                <div id="ContainingAyatContainerTitle">آیات موجود در حدیث</div>
               {% for i in summaries_containing_ayat_counter %}
                <div id="ContainingAyatObject{{i}}" class="FehrestSummaryObject">
                    {{forloop.counter}}-
                    <input type="text" placeholder="سوره" name="ContainingAyatSoore{{i}}"/>
                    <input type="text" placeholder="آیه" name="ContainingAyatAye{{i}}"/>
                </div>
                {% endfor %}
            </div>
            <div class="FloatLeft" id="FehrestSummaryAyatContainer">
                 <div id="FehrestSummaryAyatContainerTitle">فهرست آیات</div>
               {% for i in summaries_ayat_counter %}
                <div id="FehrestSummaryAyatObject{{i}}" class="FehrestSummaryObject">
                {{forloop.counter}}-
                <input type="text" placeholder="سوره" name="FehrestSoore{{i}}"/>
                <input type="text" placeholder="شماره آیه" name="FehrestAyeNo{{i}}"/>
                <input type="text" placeholder="متن آیه" name="FehrestAyeText{{i}}"/>
                <input type="text" placeholder="توضیح" name="FehrestAyeDesc{{i}}"/>

            </div>
            {% endfor %}
        </div>
            <div class="FloatLeft" id="RelatedExplanationContainer">
                 <div id="RelatedExplanationContainerTitle">توضیحات مرتبط</div>
               {% for i in related_explanation_counter %}
                <div id="RelatedExplanationObject{{i}}" class="FehrestSummaryObject">
                {{forloop.counter}}-
                <input type="text" placeholder="عبارت" name="Expression{{i}}"/>
                <input type="text" placeholder="توضیح" name="Explanation{{i}}"/>
            </div>
            {% endfor %}
        </div>
            <div class="" id="ButtonsBelow">
                <input type="button" id="MoreSummariesBoxes1" value="نمایش بیشتر برای خلاصه ها" onclick="showMoreBoxes1()">
                <input type="button" id="MoreSummariesBoxes2" value="نمایش بیشتر برای خلاصه ها" onclick="showMoreBoxes2()">
                <input type="button" id="CheckForHadisRepetition" value="بررسی تکراری بودن حدیث" onclick="showRepeatBox()">
                <Button id="SubmitButton" form="SaveAhadis" onclick="">ذخیره</Button>
            </div>
        </div>
    </form>
    <div id="RepeatBoxDiv">
        <form id="RepeatBoxForm"  action="{% url 'ahadis:check_hadis_repetition' %}" method="post">
            {% csrf_token %}
            <input id="RepeatBoxHadisText" type="text" placeholder="متن حدیث" name="HadisTextForRepetition"/>
            <br>
            <input type="button" id="CloseRepetitionBox" value="بستن" onclick="closeRepeatBox()">
            <Button id="SubmitButtonRepetition" form="RepeatBoxForm" onclick="">بررسی</Button>
        </form>
    </div>
{% endblock content %}
{% block js %}
    <script src="{% static 'ahadis/index.js' %}"></script>
{% endblock js %}

ahadis/templates/ahadis/show.html
<!DOCTYPE html>
{% extends "ahadis/base.html" %}
{% block content %}
{% load static %}
<link href="{% static 'ahadis/show.css' %}" rel="stylesheet"/>
<div id="MainContainer">
    <div id="FehrestAyat" class="Column">
            فهرست آیات
        <div>
            <button id="AyatSubjectButton" class="AyatFehrestButtons" onclick="showAyatSubject()">موضوعی</button>
            <button id="AyatSerialButton" class="AyatFehrestButtons" onclick="showAyatSerial()">سوره ها</button>
        </div>
        <div id="AyatSubject">
            subject
            <ul class="tree">
            {% for ayat_key1, ayat_value1 in fehrest.items %}
            <li class="section">
                <input type="checkbox" id="{{ayat_key1}}"/>
                <label for="{{ayat_key1}}">{{ayat_key1}}</label>
                <ul>
                    {% for ayat_key2, ayat_value2 in ayat_value1.items %}
                    <form action="{% url 'ahadis:filter_ahadis_from_fehrest_subject' %}" method="post">
                        <li class="section">
                            {% csrf_token %}
                            <input name="Subject" value="{{ayat_key2}}" type="checkbox" id="{{ayat_key2}}"/>
                            <label for="{{ayat_key2}}">{{ayat_key2}}</label>
                            <Button name="Subject" value="{{ayat_key2}}" onclick="">نمایش تمام احادیث این موضوع</Button>
                            <ul>
                                {% for ayat_value3 in ayat_value2 %}
                                <li>
                                    <form action="{% url 'ahadis:filter_ahadis_from_fehrest' %}" method="post">
                                        {% csrf_token %}
                                        <Button name="had_id" value="{{ayat_value3.had_id}}" onclick="">
                                            {{ayat_value3.summary}}
                                        </Button>
                                    </form>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </form>

                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
        </div>
        <div id="AyatSerial">
            Serial
            <ul class="tree">
            {% for ayat_serial_key, ayat_serial_value in ayat_fehrest_serial.items %}
            <li class="section">
                <input type="checkbox" id="{{ayat_serial_key}}"/>
                <label for="{{ayat_serial_key}}">{{ayat_serial_key}}</label>
                <ul>
                    {% for ayat_serial_no in ayat_serial_value %}
                    <form action="{% url 'ahadis:filter_ahadis_from_fehrest_subject' %}" method="post">
                        <li class="section">
                            {% csrf_token %}
                            <input name="AyeNo" value="{{ayat_serial_no}}" type="checkbox" id="{{ayat_serial_no}}"/>
                            <label for="{{ayat_serial_no}}">{{ayat_serial_no}}</label>
                            <Button name="Subject" value="{{ayat_key2}}" onclick="">احادیث این آیه</Button>
                        </li>
                    </form>

                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
        </div>

    </div>
    <div id="ShowBox" class="Column">
        {% for hadis in ahadis %}
        <p class="HadisMeta">{{hadis.Boo_Title}} چاپ {{hadis.Boo_Publisher}} جلد {{hadis.Had_BookVolNo}} صفحه
            {{hadis.Had_BookPageNo}}</p>
        <p id="hadis{{forloop.counter}}" class="Hadis">
            {{hadis.Had_Text}}
        </p>
        {% endfor %}
    </div>
    <div id="Fehrest" class="Column">
        فهرست مطالب
        <ul class="tree">
            {% for key1, value1 in fehrest.items %}
            <li class="section">
                <input type="checkbox" id="{{key1}}"/>
                <label for="{{key1}}">{{key1}}</label>
                <ul>
                    {% for key2, value2 in value1.items %}
                    <form action="{% url 'ahadis:filter_ahadis_from_fehrest_subject' %}" method="post">
                        <li class="section">
                            {% csrf_token %}
                            <input name="Subject" value="{{key2}}" type="checkbox" id="{{key2}}"/>
                            <label for="{{key2}}">{{key2}}</label>
                            <Button name="Subject" value="{{key2}}" onclick="">نمایش تمام احادیث این موضوع</Button>
                            <ul>
                                {% for value3 in value2 %}
                                <li>
                                    <form action="{% url 'ahadis:filter_ahadis_from_fehrest' %}" method="post">
                                        {% csrf_token %}
                                        <Button name="had_id" value="{{value3.had_id}}" onclick="">{{value3.summary}}
                                        </Button>
                                    </form>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </form>

                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div id="SearchHaidsContainer" class="CenterText">
    جستجوی حدیث
    <br>
    <form class="FlexRow" action="{% url 'ahadis:search' %}" method="post">
        {% csrf_token %}
        <div>
            شامل کلمات زیر
            <input class="InputFour" type="text" name="word1"/>
            <input class="InputFour" type="text" name="word2"/>
            <input class="InputFour" type="text" name="word3"/>
            <input class="InputFour" type="text" name="word4"/>
        </div>
        <div class="mr10">
            شامل موضوعات زیر
            <input class="InputFour mr10" type="text" name="subject1"/>
            <input class="InputFour mr10" type="text" name="subject2"/>
            <input class="InputFour" type="text" name="subject3"/>
            <input class="InputFour" type="text" name="subject4"/>
        </div>
        <Button id="SubmitButton" onclick="">جستجو</Button>
    </form>
</div>
    <script src="{% static 'ahadis/show.js' %}"></script>
{% endblock content %}